### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by SpacingBat3** [GyozaGuy/Discord-Electron#2]
In which license this project is shared right now?
Could you add the proper entry (I did a fork and would like to maintain it but don't know on which license).

I see electron is provided by the MIT license rights, so I'll soon update my repository then to that entry.

Also the project without license is not open source, see: [this site](http://opensource.stackexchange.com/q/1720/775) and [this issue](https://github.com/organicinternet/magento-configurable-simple/issues/222#issuecomment-135201411).

**Comment by GyozaGuy** [comment]
Thanks for bringing this up! I just added the MIT license.

**Comment by SpacingBat3** [comment]
> Thanks for bringing this up! I just added the MIT license.

Aprieciete that!

**Comment by SpacingBat3** [comment]
@GyozaGuy, I've adapted the repository to your license right now...
I've also done some changes in the package.json, where now:
- you're the author,
- I'm the maintainer,
- you're also the contributor.

The idea of this comes from the [AUR submission guidelines](https://wiki.archlinux.org/index.php/AUR_submission_guidelines#Rules_of_submission) 😉️.
